name: tudat-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - sphinx_rtd_theme
  - sphinx-tabs
  - sphinx-copybutton
  - sphinxcontrib
  - sphinxcontrib-contentui
  - sphinx-panels
  - nbsphinx
  - sphinx-gallery
  - ipython
  - jupyter
  - bump2version
  - Jinja2<3.1